development: &defaults
  adapter: postgresql
  username: enbake
  password: admin
  database: raffler_dev
  pool: 5
  timeout: 5000

test:
  <<: *defaults
  database: raffler_test

production:
  <<: *defaults
  database: raffler_prod
